### ISSUE TITLE
Due 2/21 - Backend Routes

### ISSUE THREAD

**Issue by cjc473** [davidcabuay/BednBrekkie#3]
# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain superfluous routes
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

**Comment by cjc473** [comment]
Changes:

* Make the GET route for users return one user instead of many (since we won't be searching for users, we'll only need this for returning current user and host information). GET /api/users/:id

**Comment by davidcabuay** [comment]
fixed

**Comment by cjc473** [comment]
Complete!
